version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env

  srv:
    build: ./
    restart: on-failure
    command: ./srv
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
volumes:
  db_volume: